### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by kjda** [bpearson/atom-phpcs#6] opened 2015-01-28 11:35 UTC
[Enter steps to reproduce below:]

1. Open any PHP file. This error keeps showing every time I interact with the open editor tab

I have PHPMD 1.5.0 and PHP_CodeSniffer version 1.5.0RC2 installed

**Atom Version**: 0.176.0
**System**: linux 3.13.0-32-generic
**Thrown From**: [atom-phpcs](https://github.com/bpearson/atom-phpcs) package, v0.6.0

### Stack Trace

Uncaught TypeError: Cannot read property 'style' of undefined

```
At /usr/share/atom/resources/app/node_modules/space-pen/lib/space-pen.js:516

TypeError: Cannot read property 'style' of undefined
  at [object Object].$.fn.isHidden (/usr/share/atom/resources/app/node_modules/space-pen/lib/space-pen.js:516:20)
  at [object Object].$.fn.isVisible (/usr/share/atom/resources/app/node_modules/space-pen/lib/space-pen.js:511:18)
  at AtomPHPCSView.module.exports.AtomPHPCSView.renderErrors (/home/mesmo/.atom/packages/atom-phpcs/lib/atom-phpcs-view.coffee:116:27)
  at AtomPHPCSView.renderErrors (/home/mesmo/.atom/packages/atom-phpcs/lib/atom-phpcs-view.coffee:1:1)
  at atom-text-editor.<anonymous> (/home/mesmo/.atom/packages/atom-phpcs/lib/atom-phpcs-view.coffee:18:8)
  at atom-text-editor.handler (/usr/share/atom/resources/app/src/space-pen-extensions.js:112:34)
  at atom-text-editor.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-text-editor.elemData.handle (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:156:19)
  at TextEditorView.jQuery.fn.trigger (/usr/share/atom/resources/app/src/space-pen-extensions.js:64:23)
  at [object Object].module.exports.React.createClass.componentDidUpdate (/usr/share/atom/resources/app/src/text-editor-component.js:273:54)
  at CallbackQueue.mixInto.notifyAll (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/CallbackQueue.js:75:22)
  at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactReconcileTransaction.js:88:26)
  at ReactReconcileTransaction.Mixin.closeAll (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:214:42)
  at ReactReconcileTransaction.Mixin.perform (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:155:16)
  at ReactUpdatesFlushTransaction.Mixin.perform (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:141:20)
  at ReactUpdatesFlushTransaction.mixInto.perform (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:98:38)
  at Object.flushBatchedUpdates (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:176:19)
  at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:214:42)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:155:16)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactDefaultBatchingStrategy.js:70:19)
  at Object.enqueueUpdate (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:209:22)
  at [object Object].ReactCompositeComponentMixin.forceUpdate (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1232:18)
  at /usr/share/atom/resources/app/src/text-editor-component.js:313:28

```

### Commands

```
     -7:05.7 project-find:show (atom-pane.pane.active)
     -7:01.0 command-palette:toggle (atom-pane.pane.active)
     -6:56.2 project-find:toggle (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-phpcs, v0.6.0
atom-ternjs, v0.2.19
autoclose-html, v0.14.0
color-picker, v1.4.4
git-log, v0.2.0
linter, v0.10.1
linter-php, v0.0.11
linter-phpcs, v0.0.12
linter-phpmd, v0.0.10
php-getters-setters, v0.2.3
project-manager, v1.15.1
seti-ui, v0.6.3

# Dev
No dev packages
```

/cc @atom/core

**Comment by abishekrsrikaanth** [comment] 2015-02-16 09:50
:+1:

**Comment by Grezvany13** [comment] 2015-02-24 16:19
Same error, even when opening non PHP files (eg. Javascript)


**Atom Version**: 0.174.0
**System**: Mac OS X 10.9.5
**Thrown From**: [atom-phpcs](https://github.com/bpearson/atom-phpcs) package, v0.6.0

### Stack Trace

Uncaught TypeError: Cannot read property 'style' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/lib/space-pen.js:516

TypeError: Cannot read property 'style' of undefined
  at [object Object].$.fn.isHidden (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/lib/space-pen.js:516:20)
  at [object Object].$.fn.isVisible (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/lib/space-pen.js:511:18)
  at AtomPHPCSView.module.exports.AtomPHPCSView.renderErrors (/Users/johandejong/.atom/packages/atom-phpcs/lib/atom-phpcs-view.coffee:116:27)
  at AtomPHPCSView.renderErrors (/Users/johandejong/.atom/packages/atom-phpcs/lib/atom-phpcs-view.coffee:1:1)
  at atom-text-editor.<anonymous> (/Users/johandejong/.atom/packages/atom-phpcs/lib/atom-phpcs-view.coffee:18:8)
  at atom-text-editor.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:112:34)
  at atom-text-editor.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-text-editor.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at TextEditorView.jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:64:23)
  at [object Object].module.exports.React.createClass.componentDidUpdate (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:273:54)
  at CallbackQueue.mixInto.notifyAll (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/CallbackQueue.js:75:22)
  at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactReconcileTransaction.js:88:26)
  at ReactReconcileTransaction.Mixin.closeAll (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:214:42)
  at ReactReconcileTransaction.Mixin.perform (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:155:16)
  at ReactUpdatesFlushTransaction.Mixin.perform (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:141:20)
  at ReactUpdatesFlushTransaction.mixInto.perform (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:98:38)
  at Object.flushBatchedUpdates (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:176:19)
  at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:214:42)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:155:16)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactDefaultBatchingStrategy.js:70:19)
  at Object.enqueueUpdate (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:209:22)
  at [object Object].ReactCompositeComponentMixin.forceUpdate (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1232:18)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:313:28

```

### Commands

```
  2x -0:03.4 core:paste (atom-text-editor#atom-phpcs.path.editor.mini)
  6x -0:00.0 core:backspace (atom-text-editor#atom-phpcs.standard.editor.mini)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "atom-light-syntax"
    ],
    "destroyEmptyPanes": false
  },
  "atom-phpcs": {
    "path": "/Applications/MAMP/bin/php/php5.5.14/bin/phpcs",
    "standard": "/Applications/MAMP/bin/php/php5.5.14/bin"
  }
}
```

### Installed Packages

```coffee
# User
atom-phpcs, v0.6.0
docblockr, v0.5.8
docs-snippets, v0.8.0
markdown-preview-plus, v0.2.0
project-colorize, v0.1.0
project-manager, v1.11.1
seti-ui, v0.3.6
tree-view-breadcrumb, v0.2.3
wakatime, v3.0.2
wordpress-api, v1.0.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by Deathgazeroo** [comment] 2015-02-24 17:21
+1
same here, OSX, Atom (only atom-phpcs installed), PHPCS installed from PEAR

**Comment by bpearson** [comment] 2015-02-25 20:34
Yeah, I am aware of this issue but haven't had enough time to fix it yet. The problem is the version of Atom has a different API so this plugin will not work. Hopefully I will get some time soon to fix it.

**Comment by Deathgazeroo** [comment] 2015-02-25 20:47
It's nothing really :) I found linter with linter-phpcs package so that
will do :)
25 lut 2015 21:35 "Benjamin Pearson" <notifications@github.com> napisa³(a):

**Comment by bpearson** [comment] 2015-02-28 09:46
Ok, it should be all fixed now. Sorry for the delay. Please update to version 0.7.0.

**Closed by bpearson** 2015-02-28 09:46 UTC
