### ISSUE TITLE
Uncaught SyntaxError: Unexpected token C in JSON at position 0

### ISSUE THREAD

**Issue by nurzaly** [bpearson/atom-phpcs#33] opened 2017-08-24 06:32 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.3 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-phpcs](https://github.com/bpearson/atom-phpcs) package 1.7.3

### Stack Trace

Uncaught SyntaxError: Unexpected token C in JSON at position 0

```
At file:///C:/Users/Nurzaly/AppData/Local/atom/app-1.19.3/resources/app/static/index.html:1

SyntaxError: Unexpected token C in JSON at position 0
    at JSON.parse (<anonymous>)
    at exit (/packages/atom-phpcs/lib/atom-phpcs.coffee:194:27)
    at triggerExitCallback (~/AppData/Local/atom/app-1.19.3/resources/app/src/buffered-process.js:338:17)
    at ~/AppData/Local/atom/app-1.19.3/resources/app/src/buffered-process.js:359:17
    at Socket.<anonymous> (~/AppData/Local/atom/app-1.19.3/resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
  3x -0:43.1.0 core:backspace (input.hidden-input)
     -0:41.1.0 core:confirm (input.hidden-input)
     -0:08.3.0 intentions:highlight (input.hidden-input)
     -0:08.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-phpcs 1.7.3 
busy-signal 1.4.3 
intentions 1.1.5 
linter 2.2.0 
linter-csslint 1.3.4 
linter-htmlhint 1.3.3 
linter-js-yaml 1.2.7 
linter-jshint 3.1.5 
linter-php 1.4.0 
linter-phpcs 1.6.7 
linter-phpmd 1.5.3 
linter-scss-lint 3.1.0 
linter-tidy 2.3.1 
linter-ui-default 1.6.7 
php-cs-fixer 4.1.0 
```

**Comment by bpearson** [comment] 2017-08-24 06:47
Can you try and run phpcs on the same file with the following args --report=json --standard=PEAR (change the standard to whatever you use). I believe it might be a problem with phpcs not returning valid json.

**Comment by bpearson** [comment] 2017-09-18 02:49
This is possibly a dupe of Issue #34, check your phpcs version is up to date, there is a bug in older versions where it would throw content outside of the JSON.

**Closed by bpearson** 2017-09-18 02:49 UTC
